import * as THREE from 'three';
import { GLTFLoader } from 'https://cdn.jsdelivr.net/npm/three@0.169.0/examples/jsm/loaders/GLTFLoader.js';
const canvas=document.querySelector('#scene3d'),scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(42,innerWidth/innerHeight,.1,100),renderer=new THREE.WebGLRenderer({canvas,alpha:true,antialias:true});
renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.18;renderer.shadowMap.enabled=true;camera.position.set(0,1.2,8);
scene.add(new THREE.HemisphereLight(0xddeeff,0x15100a,3));const key=new THREE.DirectionalLight(0xffdfaa,5);key.position.set(5,7,6);key.castShadow=true;scene.add(key);
const loader=new GLTFLoader();let car=null,plane=null;const people=[],mixers=[],wheels=[];
loader.load('https://threejs.org/examples/models/gltf/ferrari.glb',g=>{car=g.scene;car.scale.setScalar(1.15);car.position.set(3,-1.4,.2);car.rotation.y=-.5;car.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;if(/wheel|tire/i.test(o.name))wheels.push(o)}});scene.add(car)});

loader.load('https://raw.githubusercontent.com/rana-jatin/avatar-stage/main/demo/public/models/character.glb',g=>{for(let i=0;i<2;i++){const p=g.scene.clone(true);p.scale.setScalar(.72);p.position.set(-1.6-i*.7,-1.52,1.1+i*.15);p.rotation.y=-Math.PI/2;p.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true}});scene.add(p);people.push(p);const m=new THREE.AnimationMixer(p);const walk=g.animations.find(a=>/walk/i.test(a.name))||g.animations[0];m.clipAction(walk).play();mixers.push(m)}},undefined,e=>console.warn('People',e));
const clock=new THREE.Clock();let sy=0,cycle=0;
function animate(){requestAnimationFrame(animate);const dt=clock.getDelta(),t=performance.now()*.001;cycle=t%9;mixers.forEach(m=>m.update(dt));people.forEach((p,i)=>{const u=Math.min(cycle/5.4,1);p.position.x=-1.6-i*.7+u*(3.2+i*.55);p.visible=cycle<6;p.rotation.y=-Math.PI/2});if(car){const depart=cycle>6.4?Math.min((cycle-6.4)/2.2,1):0;wheels.forEach(w=>w.rotation.x-=(depart>.01?.2:.02));car.position.x=3-Math.min(sy/innerHeight,1)*1.4+depart*5.5;car.rotation.y=-.5}const rs=document.querySelector('#rideStatus');if(rs)rs.textContent=cycle<5.3?'Les passagers approchent':cycle<6.4?'Embarquement en cours':'Départ vers votre destination';renderer.render(scene,camera)}animate();
addEventListener('scroll',()=>{sy=scrollY;const road=document.querySelector('.road'),r=road.getBoundingClientRect(),p=Math.max(0,Math.min(1,(innerHeight-r.top)/(innerHeight+r.height)));const taxi=document.querySelector('#roadTaxi');if(taxi){taxi.classList.toggle('moving',p>0&&p<1);taxi.style.transform='translateX('+(-p*(innerWidth+520))+'px) scale('+(0.72+p*.36)+')'}document.querySelector('.heroBg').style.transform='scale(1.08) translateY('+Math.min(sy*.045,38)+'px)'});
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
const io=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('on')),{threshold:.12});document.querySelectorAll('.reveal').forEach(x=>io.observe(x));document.querySelector('#menu').onclick=()=>document.body.classList.toggle('nav-open');document.querySelectorAll('nav a').forEach(a=>a.onclick=()=>document.body.classList.remove('nav-open'));document.querySelector('#form').onsubmit=e=>{e.preventDefault();document.querySelector('#ok').textContent='✓ Demande préparée. Prototype seulement : aucun taxi n’a encore été réservé.'};